import{S as g,i as l}from"./assets/vendor-BrddEoy-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const h="https://pixabay.com/api/",b="47358602-d5490533da2bc88f2f38f5bcb";function L(n,r=1){const i=`${h}?key=${b}&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}`;return fetch(i).then(o=>{if(!o.ok)throw new Error("Failed to fetch images");return o.json()}).then(o=>o.hits).catch(o=>{console.error(o)})}function $(n){return n.map(({webformatURL:r,largeImageURL:i,tags:o,likes:e,views:t,comments:a,downloads:p})=>`
        <li class="gallery-list-item">
          <a href="${i}" class="gallery-list-link">
            <img class="gallery-img" src="${r}" alt="${o}" />
          </a>
          <div class="img-info">
            <p><b>Likes:</b> ${e}</p>
            <p><b>Views:</b> ${t}</p>
            <p><b>Comments:</b> ${a}</p>
            <p><b>Downloads:</b> ${p}</p>
          </div>
        </li>`).join("")}function P(n){n.innerHTML=""}function f(){new g(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250})}const c=document.querySelector(".search-form"),d=document.querySelector(".gallery"),m=document.querySelector(".loader");let u="",y=1;f();c.addEventListener("submit",n=>{n.preventDefault();const r=c.elements.searchQuery.value.trim();if(!r){l.warning({title:"Warning",message:"Please enter a search query!"});return}u=r,y=1,P(d),q(u)});function q(n){v(),L(n,y).then(r=>{if(r.length===0){l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),s();return}const i=$(r);d.insertAdjacentHTML("beforeend",i),f(),s()}).catch(r=>{l.error({title:"Error",message:"Failed to load images. Please try again!"}),console.error("Error:",r),s()}).finally(()=>w())}function v(){m.style.display="inline-block"}function w(){m.style.display="none"}function s(){c.elements.searchQuery.value=""}
//# sourceMappingURL=index.js.map
